FILEFINDER_DIR= FileFinder
ARGSPARSER_DIR= ArgsParser

.PHONY: all FileFinder ArgsParser

all: ArgsParser FileFinder

FileFinder:
	cd $(FILEFINDER_DIR) && \
	make

ArgsParser:
	cd $(ARGSPARSER_DIR) && \
	make